### ISSUE TITLE
[BUG]: getting stuck inside AddCustomServerRequestHandler

### ISSUE THREAD

**Issue by jackfreed** [xelaj/mtproto#97] opened 2021-06-22 06:47 UTC
i have this very short example of where i want to mark messages as read:

```
client.AddCustomServerRequestHandler(func(update interface{}) bool {
	switch u := update.(type) {
	case *telegram.UpdateShortMessage:
		peer := &telegram.InputPeerUser{
			UserID:     123,
			AccessHash: 456,
		}

		_, err := client.MessagesReadHistory(peer, u.ID)
		if err != nil {
			panic(err)
		}

		print("here") <----------------
	}

	return false
})

state, err := client.UpdatesGetState()
if err != nil {
	panic(err)
}
```

the message is being marked as read on the senders device but i am never getting to "here"
so all other subsequent messages are stuck as well because AddCustomServerRequestHandler never returns.

**Comment by quenbyako** [comment] 2021-06-22 17:49
@jackfreed try to add some debug messages **before** switch statment, maybe you don't recieve any requests at all

**Comment by jackfreed** [comment] 2021-06-22 18:00
if i send another message its not coming, but that does not matter since the call is not returning to **print("here")**

**Comment by quenbyako** [comment] 2021-06-22 18:15
@jackfreed all registred callbacks are called after any request from mtproto recieved until any callback returns `true`. So, it could be possible 2 problems:

1) you added some callback before, which returning `true`, but in your case description, looks like this is not exact problem
2) telegram doesn't send you **any** request, which is really strange, but it is possible case, i don't know why, but i got this problem sometimes, so maybe this issue affected to your client (idk why, need to ask tg devs)
3) most realistic case, you receiving "long" updates which contains large amount of additional info, so your switch case doesn't process them at all.

So try to check first, does your callback, well, calling at all. maybe you mismatched message type.

**Comment by quenbyako** [comment] 2021-06-30 19:10
@jackfreed i need to close this issue, cause i can't reproduce this bug.

You can always reopen it, don't worry, i'll come back, if you still have any issues (but before reopening, please, add a bit more info, this will help a lot)

**Closed by quenbyako** 2021-06-30 19:10 UTC
Labels: bug

**Comment by jackfreed** [comment] 2021-07-09 10:03
just to make sure, you got the fact that:


`		_, err := client.MessagesReadHistory(peer, u.ID)
`

**is being executed** (blue tick on the remote side) but the print statement is never reached:

`		print("here") <----------------
`

meaning the request handler also never returns

**Comment by quenbyako** [comment] 2021-07-11 13:53
@jackfreed got your note, I'll try to reproduce it again (but honestly, i don't understand, where it can _possibly_ be any issue)
